# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d3f580c716953239ebabf6a0fe9a7d924d75427f7b521fb14646e9d8755b03ffce5ac2ec63b0c55aefe5906b28480a9262b9a4d7abb1ad2b4247b316290146

test:
  secret_key_base: 8f2adb70fa071b5b117c5cbc64566d5b2810fd716beb34726e82b39784a16fdcb7593601587cbf4a37f570bce9d719fa326c25355fca51fa6a5965561c37c62e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
